# Generated by Django 5.0.2 on 2024-02-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_space_finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdetails',
            name='operating_hours',
            field=models.CharField(max_length=100),
        ),
    ]
