# Generated by Django 5.0.2 on 2024-02-24 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_space_finder', '0002_alter_buildingdetails_operating_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingdetails',
            name='operating_hours',
        ),
    ]
