# Generated by Django 5.0.2 on 2024-02-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_space_finder', '0005_buildingdetails_operating_start_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdetails',
            name='operating_end_hours',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='operating_start_hours',
            field=models.TimeField(blank=True),
        ),
    ]
