# Generated by Django 4.1.7 on 2024-02-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_space_finder', '0006_alter_buildingdetails_operating_end_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200)),
                ('building_name', models.CharField(max_length=200)),
                ('floor_number', models.IntegerField(default=0)),
                ('operating_start_hours', models.TimeField(blank=True)),
                ('operating_end_hours', models.TimeField(blank=True)),
                ('number_of_seats', models.IntegerField()),
                ('outlet_availability', models.BooleanField(default=False)),
                ('tables_availability', models.BooleanField(default=False)),
                ('open_space_availability', models.BooleanField(default=False)),
                ('coordinate_latitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=9)),
                ('coordinate_longitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=9)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='BuildingDetails',
        ),
    ]
