# Generated by Django 4.1.7 on 2024-02-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_space_finder', '0008_mymodel_post_rental_samplemodel_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetails',
            name='distance_to_user',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
