# Generated by Django 4.1.7 on 2024-02-25 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_space_finder', '0009_roomdetails_distance_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdetails',
            name='distance_to_user',
        ),
    ]
