# Generated by Django 4.1.7 on 2024-02-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_space_finder', '0010_remove_roomdetails_distance_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetails',
            name='white_board_availability',
            field=models.BooleanField(default=False),
        ),
    ]
